### ISSUE TITLE
大列表DiffUtil计算很慢有没有办法优化

### ISSUE THREAD

**Issue by 821938089** [xiaocydx/Recycler#1]
我目前想到的思路是只计算可视区域附近的变化，但是不知道怎么实现

**Comment by xiaocydx** [comment]
因为我不太清楚你的场景，所以只能根据以往的经验给出一些建议。

#### 1. 调用`ListAdapter.calculateDiffOnMainThread()`
有时不一定是DiffUtil计算很慢，可能是工作线程跟主线程之间的调度很慢，导致列表推迟更新。我曾在低端机上碰到过这个问题，当时改为了在主线程执行计算。

#### 2.将item数据类的属性抽取出来
比如列表有两种模式，一种滑动浏览，一种拖动排序。当切换到排序模式时，`itemView`显示图标提示可拖动。

通常我的做法不是在item数据类中定义`mode`属性去更新列表，而是在列表数据外定义`mode`属性。更改`mode`

**Comment by xiaocydx** [comment]
因为我不太清楚你的场景，所以只能根据以往的经验给出一些建议。

#### 1. 调用`ListAdapter.calculateDiffOnMainThread()`
有时不一定是DiffUtil计算很慢，可能是工作线程跟主线程之间的调度很慢，导致列表推迟更新。我曾在低端机上碰到过这个问题，当时改为了在主线程执行计算。

#### 2.不使用DiffUtill
如果你的场景能得知具体更新操作，比如`addItem()`、`removeItem()`等等，建议就做具体更新，不使用DiffUtil。我在项目中使用DiffUtil的场景主要是：重新获取数据刷新列表、页面恢复活跃状态、多级列表展开关闭。

#### 3.将item数据类的属性抽取出来
比如列表有两种模式，一种滑动浏览，一种拖动排序。当切换到排序模式时，`itemView`显示图标提示可拖动。

通常我的做法不是在item数据类中定义`mode`属性去更新列表，而是在列表数据外定义`mode`属性。
当更改`mode`属性时，同步调用`adapter.notifyItemRangeChanged(0, adapter.itemCount, payload)`。

传入`adapter.itemCount`不会有冗余更新问题，RecyclerView的布局流程只对当前子View做更新（可以理解为你所说的可视区域）。

#### 4.调用`adapter.notifyDataSetChanged()`
不使用DiffUtil，调用`adapter.notifyDataSetChanged()`也是处理无法得知具体更新操作的一种方式，只是我比较少用这个函数，因为它产生的副作用较多。

如果你使用的是`ListAdapter`，那么调用方式是：
```
adapter.clear()
adapter.insertItems(items)
adapter.notifyDataSetChanged()
```

**Comment by xiaocydx** [comment]
如果以上建议无法解决问题，请添加我的微信，根据你的场景讨论下解决方案。
![微信图片_20240830091151](https://github.com/user-attachments/assets/fa38d22d-8a11-45df-8b01-005520dc28b2)
